// International Airport Database
// Contains 200 major international airports with IATA codes, names, and cities

interface Airport {
  code: string;
  name: string;
  city: string;
  country: string;
}

const airports: Airport[] = [
  // Asia
  { code: 'HAN', name: 'Noi Bai International Airport', city: 'Hanoi', country: 'Vietnam' },
  { code: 'SGN', name: 'Tan Son Nhat International Airport', city: 'Ho Chi Minh City', country: 'Vietnam' },
  { code: 'DAD', name: 'Da Nang International Airport', city: 'Da Nang', country: 'Vietnam' },
  { code: 'CXR', name: 'Cam Ranh International Airport', city: 'Nha Trang', country: 'Vietnam' },
  { code: 'PQC', name: 'Phu Quoc International Airport', city: 'Phu Quoc', country: 'Vietnam' },
  { code: 'HUI', name: 'Phu Bai International Airport', city: 'Hue', country: 'Vietnam' },
  { code: 'BKK', name: 'Suvarnabhumi Airport', city: 'Bangkok', country: 'Thailand' },
  { code: 'DMK', name: 'Don Mueang International Airport', city: 'Bangkok', country: 'Thailand' },
  { code: 'CNX', name: 'Chiang Mai International Airport', city: 'Chiang Mai', country: 'Thailand' },
  { code: 'HKT', name: 'Phuket International Airport', city: 'Phuket', country: 'Thailand' },
  { code: 'SIN', name: 'Singapore Changi Airport', city: 'Singapore', country: 'Singapore' },
  { code: 'KUL', name: 'Kuala Lumpur International Airport', city: 'Kuala Lumpur', country: 'Malaysia' },
  { code: 'CGK', name: 'Soekarno-Hatta International Airport', city: 'Jakarta', country: 'Indonesia' },
  { code: 'DPS', name: 'Ngurah Rai International Airport', city: 'Denpasar', country: 'Indonesia' },
  { code: 'MNL', name: 'Ninoy Aquino International Airport', city: 'Manila', country: 'Philippines' },
  { code: 'CEB', name: 'Mactan-Cebu International Airport', city: 'Cebu', country: 'Philippines' },
  { code: 'ICN', name: 'Incheon International Airport', city: 'Seoul', country: 'South Korea' },
  { code: 'GMP', name: 'Gimpo International Airport', city: 'Seoul', country: 'South Korea' },
  { code: 'NRT', name: 'Narita International Airport', city: 'Tokyo', country: 'Japan' },
  { code: 'HND', name: 'Haneda Airport', city: 'Tokyo', country: 'Japan' },
  { code: 'KIX', name: 'Kansai International Airport', city: 'Osaka', country: 'Japan' },
  { code: 'PEK', name: 'Beijing Capital International Airport', city: 'Beijing', country: 'China' },
  { code: 'PVG', name: 'Shanghai Pudong International Airport', city: 'Shanghai', country: 'China' },
  { code: 'CAN', name: 'Guangzhou Baiyun International Airport', city: 'Guangzhou', country: 'China' },
  { code: 'HKG', name: 'Hong Kong International Airport', city: 'Hong Kong', country: 'China' },
  { code: 'TPE', name: 'Taiwan Taoyuan International Airport', city: 'Taipei', country: 'Taiwan' },
  { code: 'DEL', name: 'Indira Gandhi International Airport', city: 'New Delhi', country: 'India' },
  { code: 'BOM', name: 'Chhatrapati Shivaji Maharaj International Airport', city: 'Mumbai', country: 'India' },
  { code: 'BLR', name: 'Kempegowda International Airport', city: 'Bangalore', country: 'India' },
  { code: 'CCU', name: 'Netaji Subhas Chandra Bose International Airport', city: 'Kolkata', country: 'India' },
  { code: 'DAC', name: 'Hazrat Shahjalal International Airport', city: 'Dhaka', country: 'Bangladesh' },
  { code: 'CMB', name: 'Bandaranaike International Airport', city: 'Colombo', country: 'Sri Lanka' },
  { code: 'KTM', name: 'Tribhuvan International Airport', city: 'Kathmandu', country: 'Nepal' },
  { code: 'ISB', name: 'Islamabad International Airport', city: 'Islamabad', country: 'Pakistan' },
  { code: 'LHE', name: 'Allama Iqbal International Airport', city: 'Lahore', country: 'Pakistan' },
  { code: 'DXB', name: 'Dubai International Airport', city: 'Dubai', country: 'UAE' },
  { code: 'AUH', name: 'Abu Dhabi International Airport', city: 'Abu Dhabi', country: 'UAE' },
  { code: 'DOH', name: 'Hamad International Airport', city: 'Doha', country: 'Qatar' },
  { code: 'RUH', name: 'King Khalid International Airport', city: 'Riyadh', country: 'Saudi Arabia' },
  { code: 'JED', name: 'King Abdulaziz International Airport', city: 'Jeddah', country: 'Saudi Arabia' },
  { code: 'IST', name: 'Istanbul Airport', city: 'Istanbul', country: 'Turkey' },
  { code: 'SAW', name: 'Sabiha Gökçen International Airport', city: 'Istanbul', country: 'Turkey' },
  { code: 'TLV', name: 'Ben Gurion Airport', city: 'Tel Aviv', country: 'Israel' },
  { code: 'CAI', name: 'Cairo International Airport', city: 'Cairo', country: 'Egypt' },
  { code: 'JNB', name: 'O.R. Tambo International Airport', city: 'Johannesburg', country: 'South Africa' },
  { code: 'CPT', name: 'Cape Town International Airport', city: 'Cape Town', country: 'South Africa' },
  { code: 'NBO', name: 'Jomo Kenyatta International Airport', city: 'Nairobi', country: 'Kenya' },
  { code: 'LOS', name: 'Murtala Muhammed International Airport', city: 'Lagos', country: 'Nigeria' },
  { code: 'LHR', name: 'Heathrow Airport', city: 'London', country: 'United Kingdom' },
  { code: 'LGW', name: 'Gatwick Airport', city: 'London', country: 'United Kingdom' },
  { code: 'STN', name: 'Stansted Airport', city: 'London', country: 'United Kingdom' },
  { code: 'MAN', name: 'Manchester Airport', city: 'Manchester', country: 'United Kingdom' },
  { code: 'EDI', name: 'Edinburgh Airport', city: 'Edinburgh', country: 'United Kingdom' },
  { code: 'CDG', name: 'Charles de Gaulle Airport', city: 'Paris', country: 'France' },
  { code: 'ORY', name: 'Orly Airport', city: 'Paris', country: 'France' },
  { code: 'FRA', name: 'Frankfurt Airport', city: 'Frankfurt', country: 'Germany' },
  { code: 'MUC', name: 'Munich Airport', city: 'Munich', country: 'Germany' },
  { code: 'BER', name: 'Berlin Brandenburg Airport', city: 'Berlin', country: 'Germany' },
  { code: 'AMS', name: 'Amsterdam Airport Schiphol', city: 'Amsterdam', country: 'Netherlands' },
  { code: 'MAD', name: 'Adolfo Suárez Madrid–Barajas Airport', city: 'Madrid', country: 'Spain' },
  { code: 'BCN', name: 'Barcelona–El Prat Airport', city: 'Barcelona', country: 'Spain' },
  { code: 'FCO', name: 'Leonardo da Vinci International Airport', city: 'Rome', country: 'Italy' },
  { code: 'MXP', name: 'Milan Malpensa Airport', city: 'Milan', country: 'Italy' },
  { code: 'ZRH', name: 'Zurich Airport', city: 'Zurich', country: 'Switzerland' },
  { code: 'VIE', name: 'Vienna International Airport', city: 'Vienna', country: 'Austria' },
  { code: 'BRU', name: 'Brussels Airport', city: 'Brussels', country: 'Belgium' },
  { code: 'ARN', name: 'Stockholm Arlanda Airport', city: 'Stockholm', country: 'Sweden' },
  { code: 'CPH', name: 'Copenhagen Airport', city: 'Copenhagen', country: 'Denmark' },
  { code: 'OSL', name: 'Oslo Airport', city: 'Oslo', country: 'Norway' },
  { code: 'HEL', name: 'Helsinki Airport', city: 'Helsinki', country: 'Finland' },
  { code: 'WAW', name: 'Warsaw Chopin Airport', city: 'Warsaw', country: 'Poland' },
  { code: 'PRG', name: 'Václav Havel Airport Prague', city: 'Prague', country: 'Czech Republic' },
  { code: 'BUD', name: 'Budapest Ferenc Liszt International Airport', city: 'Budapest', country: 'Hungary' },
  { code: 'ATH', name: 'Athens International Airport', city: 'Athens', country: 'Greece' },
  { code: 'LIS', name: 'Lisbon Airport', city: 'Lisbon', country: 'Portugal' },
  { code: 'OPO', name: 'Porto Airport', city: 'Porto', country: 'Portugal' },
  { code: 'DUB', name: 'Dublin Airport', city: 'Dublin', country: 'Ireland' },
  { code: 'KEF', name: 'Keflavík International Airport', city: 'Reykjavik', country: 'Iceland' },
  { code: 'JFK', name: 'John F. Kennedy International Airport', city: 'New York', country: 'United States' },
  { code: 'LAX', name: 'Los Angeles International Airport', city: 'Los Angeles', country: 'United States' },
  { code: 'ORD', name: 'O\'Hare International Airport', city: 'Chicago', country: 'United States' },
  { code: 'ATL', name: 'Hartsfield-Jackson Atlanta International Airport', city: 'Atlanta', country: 'United States' },
  { code: 'DFW', name: 'Dallas/Fort Worth International Airport', city: 'Dallas', country: 'United States' },
  { code: 'DEN', name: 'Denver International Airport', city: 'Denver', country: 'United States' },
  { code: 'SFO', name: 'San Francisco International Airport', city: 'San Francisco', country: 'United States' },
  { code: 'LAS', name: 'McCarran International Airport', city: 'Las Vegas', country: 'United States' },
  { code: 'MIA', name: 'Miami International Airport', city: 'Miami', country: 'United States' },
  { code: 'BOS', name: 'Logan International Airport', city: 'Boston', country: 'United States' },
  { code: 'SEA', name: 'Seattle-Tacoma International Airport', city: 'Seattle', country: 'United States' },
  { code: 'IAH', name: 'George Bush Intercontinental Airport', city: 'Houston', country: 'United States' },
  { code: 'PHX', name: 'Phoenix Sky Harbor International Airport', city: 'Phoenix', country: 'United States' },
  { code: 'MCO', name: 'Orlando International Airport', city: 'Orlando', country: 'United States' },
  { code: 'DTW', name: 'Detroit Metropolitan Airport', city: 'Detroit', country: 'United States' },
  { code: 'CLT', name: 'Charlotte Douglas International Airport', city: 'Charlotte', country: 'United States' },
  { code: 'FLL', name: 'Fort Lauderdale-Hollywood International Airport', city: 'Fort Lauderdale', country: 'United States' },
  { code: 'YYZ', name: 'Toronto Pearson International Airport', city: 'Toronto', country: 'Canada' },
  { code: 'YVR', name: 'Vancouver International Airport', city: 'Vancouver', country: 'Canada' },
  { code: 'YUL', name: 'Montréal-Trudeau International Airport', city: 'Montreal', country: 'Canada' },
  { code: 'YYC', name: 'Calgary International Airport', city: 'Calgary', country: 'Canada' },
  { code: 'YOW', name: 'Ottawa Macdonald-Cartier International Airport', city: 'Ottawa', country: 'Canada' },
  { code: 'MEX', name: 'Benito Juárez International Airport', city: 'Mexico City', country: 'Mexico' },
  { code: 'GDL', name: 'Miguel Hidalgo y Costilla International Airport', city: 'Guadalajara', country: 'Mexico' },
  { code: 'MTY', name: 'General Mariano Escobedo International Airport', city: 'Monterrey', country: 'Mexico' },
  { code: 'CUN', name: 'Cancún International Airport', city: 'Cancun', country: 'Mexico' },
  { code: 'GRU', name: 'São Paulo/Guarulhos International Airport', city: 'São Paulo', country: 'Brazil' },
  { code: 'GIG', name: 'Rio de Janeiro/Galeão International Airport', city: 'Rio de Janeiro', country: 'Brazil' },
  { code: 'BSB', name: 'Brasília International Airport', city: 'Brasília', country: 'Brazil' },
  { code: 'EZE', name: 'Ministro Pistarini International Airport', city: 'Buenos Aires', country: 'Argentina' },
  { code: 'SCL', name: 'Arturo Merino Benítez International Airport', city: 'Santiago', country: 'Chile' },
  { code: 'LIM', name: 'Jorge Chávez International Airport', city: 'Lima', country: 'Peru' },
  { code: 'BOG', name: 'El Dorado International Airport', city: 'Bogotá', country: 'Colombia' },
  { code: 'MDE', name: 'José María Córdova International Airport', city: 'Medellín', country: 'Colombia' },
  { code: 'CCS', name: 'Simón Bolívar International Airport', city: 'Caracas', country: 'Venezuela' },
  { code: 'UIO', name: 'Mariscal Sucre International Airport', city: 'Quito', country: 'Ecuador' },
  { code: 'GYE', name: 'José Joaquín de Olmedo International Airport', city: 'Guayaquil', country: 'Ecuador' },
  { code: 'ASU', name: 'Silvio Pettirossi International Airport', city: 'Asunción', country: 'Paraguay' },
  { code: 'MVD', name: 'Carrasco International Airport', city: 'Montevideo', country: 'Uruguay' },
  { code: 'SYD', name: 'Sydney Airport', city: 'Sydney', country: 'Australia' },
  { code: 'MEL', name: 'Melbourne Airport', city: 'Melbourne', country: 'Australia' },
  { code: 'BNE', name: 'Brisbane Airport', city: 'Brisbane', country: 'Australia' },
  { code: 'PER', name: 'Perth Airport', city: 'Perth', country: 'Australia' },
  { code: 'ADL', name: 'Adelaide Airport', city: 'Adelaide', country: 'Australia' },
  { code: 'AKL', name: 'Auckland Airport', city: 'Auckland', country: 'New Zealand' },
  { code: 'WLG', name: 'Wellington Airport', city: 'Wellington', country: 'New Zealand' },
  { code: 'CHC', name: 'Christchurch Airport', city: 'Christchurch', country: 'New Zealand' },
  { code: 'NAN', name: 'Nadi International Airport', city: 'Nadi', country: 'Fiji' },
  { code: 'PPT', name: 'Faa\'a International Airport', city: 'Papeete', country: 'French Polynesia' },
  { code: 'HNL', name: 'Daniel K. Inouye International Airport', city: 'Honolulu', country: 'United States' },
  { code: 'ANC', name: 'Ted Stevens Anchorage International Airport', city: 'Anchorage', country: 'United States' },
  { code: 'FAI', name: 'Fairbanks International Airport', city: 'Fairbanks', country: 'United States' },
  { code: 'JNU', name: 'Juneau International Airport', city: 'Juneau', country: 'United States' },
  { code: 'KOA', name: 'Kona International Airport', city: 'Kailua-Kona', country: 'United States' },
  { code: 'LIH', name: 'Lihue Airport', city: 'Lihue', country: 'United States' },
  { code: 'OGG', name: 'Kahului Airport', city: 'Kahului', country: 'United States' },
  { code: 'ITO', name: 'Hilo International Airport', city: 'Hilo', country: 'United States' },
  { code: 'BQN', name: 'Rafael Hernández Airport', city: 'Aguadilla', country: 'Puerto Rico' },
  { code: 'SJU', name: 'Luis Muñoz Marín International Airport', city: 'San Juan', country: 'Puerto Rico' },
  { code: 'PSE', name: 'Mercedita Airport', city: 'Ponce', country: 'Puerto Rico' },
  { code: 'MAZ', name: 'Eugenio María de Hostos Airport', city: 'Mayagüez', country: 'Puerto Rico' },
  { code: 'VQS', name: 'Antonio Rivera Rodríguez Airport', city: 'Vieques', country: 'Puerto Rico' },
  { code: 'BZE', name: 'Philip S. W. Goldson International Airport', city: 'Belize City', country: 'Belize' },
  { code: 'GUA', name: 'La Aurora International Airport', city: 'Guatemala City', country: 'Guatemala' },
  { code: 'SAL', name: 'Monseñor Óscar Arnulfo Romero International Airport', city: 'San Salvador', country: 'El Salvador' },
  { code: 'TGU', name: 'Toncontín International Airport', city: 'Tegucigalpa', country: 'Honduras' },
  { code: 'MGA', name: 'Augusto C. Sandino International Airport', city: 'Managua', country: 'Nicaragua' },
  { code: 'SJO', name: 'Juan Santamaría International Airport', city: 'San José', country: 'Costa Rica' },
  { code: 'PTY', name: 'Tocumen International Airport', city: 'Panama City', country: 'Panama' },
  { code: 'HAV', name: 'José Martí International Airport', city: 'Havana', country: 'Cuba' },
  { code: 'SDQ', name: 'Las Américas International Airport', city: 'Santo Domingo', country: 'Dominican Republic' },
  { code: 'PUJ', name: 'Punta Cana International Airport', city: 'Punta Cana', country: 'Dominican Republic' },
  { code: 'STI', name: 'Cibao International Airport', city: 'Santiago', country: 'Dominican Republic' },
  { code: 'KIN', name: 'Norman Manley International Airport', city: 'Kingston', country: 'Jamaica' },
  { code: 'MBJ', name: 'Sangster International Airport', city: 'Montego Bay', country: 'Jamaica' },
  { code: 'NAS', name: 'Lynden Pindling International Airport', city: 'Nassau', country: 'Bahamas' },
  { code: 'FPO', name: 'Grand Bahama International Airport', city: 'Freeport', country: 'Bahamas' },
  { code: 'GCM', name: 'Owen Roberts International Airport', city: 'George Town', country: 'Cayman Islands' },
  { code: 'UVF', name: 'Hewanorra International Airport', city: 'Vieux Fort', country: 'Saint Lucia' },
  { code: 'BGI', name: 'Grantley Adams International Airport', city: 'Bridgetown', country: 'Barbados' },
  { code: 'POS', name: 'Piarco International Airport', city: 'Port of Spain', country: 'Trinidad and Tobago' },
  { code: 'GEO', name: 'Cheddi Jagan International Airport', city: 'Georgetown', country: 'Guyana' },
  { code: 'PBM', name: 'Johan Adolf Pengel International Airport', city: 'Paramaribo', country: 'Suriname' },
  { code: 'CAY', name: 'Cayenne Félix Eboué Airport', city: 'Cayenne', country: 'French Guiana' },
  { code: 'BCB', name: 'Boa Vista International Airport', city: 'Boa Vista', country: 'Brazil' },
  { code: 'MAO', name: 'Eduardo Gomes International Airport', city: 'Manaus', country: 'Brazil' },
  { code: 'BEL', name: 'Val de Cans International Airport', city: 'Belém', country: 'Brazil' },
  { code: 'FOR', name: 'Pinto Martins International Airport', city: 'Fortaleza', country: 'Brazil' },
  { code: 'REC', name: 'Recife/Guararapes International Airport', city: 'Recife', country: 'Brazil' },
  { code: 'SSA', name: 'Salvador International Airport', city: 'Salvador', country: 'Brazil' },
  { code: 'BHZ', name: 'Tancredo Neves International Airport', city: 'Belo Horizonte', country: 'Brazil' },
  { code: 'CWB', name: 'Afonso Pena International Airport', city: 'Curitiba', country: 'Brazil' },
  { code: 'POA', name: 'Salgado Filho International Airport', city: 'Porto Alegre', country: 'Brazil' },
  { code: 'FLN', name: 'Hercílio Luz International Airport', city: 'Florianópolis', country: 'Brazil' },
  { code: 'CGR', name: 'Campo Grande International Airport', city: 'Campo Grande', country: 'Brazil' },
  { code: 'CGB', name: 'Marechal Rondon International Airport', city: 'Cuiabá', country: 'Brazil' },
  { code: 'GYN', name: 'Santa Genoveva Airport', city: 'Goiânia', country: 'Brazil' },
  { code: 'VCP', name: 'Viracopos International Airport', city: 'Campinas', country: 'Brazil' },
  { code: 'CGH', name: 'Congonhas Airport', city: 'São Paulo', country: 'Brazil' },
  { code: 'SDU', name: 'Santos Dumont Airport', city: 'Rio de Janeiro', country: 'Brazil' },
  { code: 'NAT', name: 'São Gonçalo do Amarante International Airport', city: 'Natal', country: 'Brazil' },
  { code: 'JPA', name: 'Presidente Castro Pinto International Airport', city: 'João Pessoa', country: 'Brazil' },
  { code: 'MCP', name: 'Macapá International Airport', city: 'Macapá', country: 'Brazil' },
  { code: 'AJU', name: 'Santa Maria Airport', city: 'Aracaju', country: 'Brazil' },
  { code: 'TBS', name: 'Tbilisi International Airport', city: 'Tbilisi', country: 'Georgia' },
  { code: 'KUT', name: 'Kutaisi International Airport', city: 'Kutaisi', country: 'Georgia' },
  { code: 'BAT', name: 'Batumi International Airport', city: 'Batumi', country: 'Georgia' },
  { code: 'EVN', name: 'Zvartnots International Airport', city: 'Yerevan', country: 'Armenia' },
  { code: 'GYD', name: 'Heydar Aliyev International Airport', city: 'Baku', country: 'Azerbaijan' },
  { code: 'TAS', name: 'Tashkent International Airport', city: 'Tashkent', country: 'Uzbekistan' },
  { code: 'ALA', name: 'Almaty International Airport', city: 'Almaty', country: 'Kazakhstan' },
  { code: 'NQZ', name: 'Nursultan Nazarbayev International Airport', city: 'Nur-Sultan', country: 'Kazakhstan' },
  { code: 'FRU', name: 'Manas International Airport', city: 'Bishkek', country: 'Kyrgyzstan' },
  { code: 'DUS', name: 'Düsseldorf Airport', city: 'Düsseldorf', country: 'Germany' },
  { code: 'CGN', name: 'Cologne Bonn Airport', city: 'Cologne', country: 'Germany' },
  { code: 'HAM', name: 'Hamburg Airport', city: 'Hamburg', country: 'Germany' },
  { code: 'STR', name: 'Stuttgart Airport', city: 'Stuttgart', country: 'Germany' },
  { code: 'NUE', name: 'Nuremberg Airport', city: 'Nuremberg', country: 'Germany' },
  { code: 'LEJ', name: 'Leipzig/Halle Airport', city: 'Leipzig', country: 'Germany' },
  { code: 'DRS', name: 'Dresden Airport', city: 'Dresden', country: 'Germany' },
  { code: 'HAJ', name: 'Hannover Airport', city: 'Hannover', country: 'Germany' },
  { code: 'BRE', name: 'Bremen Airport', city: 'Bremen', country: 'Germany' },
];

// Helper function to search airports
export const searchAirports = (query: string): Airport[] => {
  if (query.length < 2) return [];
  
  const searchTerm = query.toLowerCase();
  return airports.filter(airport => 
    airport.code.toLowerCase().includes(searchTerm) ||
    airport.city.toLowerCase().includes(searchTerm) ||
    airport.name.toLowerCase().includes(searchTerm)
  ).slice(0, 8); // Limit to 8 suggestions
};

export { Airport };
export default airports; 